/**
 * Plain-text accessibility report for "Download report" (DESIGN.md §9c).
 * Deterministic: no dates, no random ids.
 */
import type { AssembledDoc, ReportEntry } from '../lib/types';

export function reportLine(e: ReportEntry): string {
  const where = e.sectionTitle ? ` (${e.sectionTitle})` : '';
  const n = e.count !== undefined && e.count > 1 ? ` [${e.count}]` : '';
  return `${e.message}${n}${where}`;
}

function block(heading: string, entries: ReportEntry[]): string[] {
  const lines = [`${heading} (${entries.length})`, ''.padEnd(heading.length + 4, '-')];
  if (entries.length === 0) lines.push('(none)');
  for (const e of entries) lines.push(`- ${reportLine(e)}`);
  lines.push('');
  return lines;
}

export function buildReportText(doc: AssembledDoc, courseTitle: string): string {
  const lines: string[] = [
    `Accessibility report: ${courseTitle}`,
    'Generated by Syllabus Generator. This report is not part of the syllabus file.',
    '',
    ...block('FIXED AUTOMATICALLY', doc.report.fixed),
    ...block('STILL NEEDS YOU', doc.report.todo),
  ];
  if (doc.report.info.length > 0) lines.push(...block('NOTES', doc.report.info));
  return lines.join('\n');
}
